---
title: "Thesis writeup analysis scripts and plots"
output:
  html_document:
    number_sections: false
    
knit: (function(input, ...) {
    rmarkdown::render(
      input,
      knit_root_dir = rprojroot::find_rstudio_root_file(),
      output_file = paste0(
      rprojroot::find_rstudio_root_file(),
      '/results/',
      'chose_sparse_paradigm_2_3_qc_filtered_',Sys.Date(),'.html'

      ),
      envir = globalenv()
    )
  })
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

# Suppress summarise info
options(dplyr.summarise.inform = FALSE)

```

```{r load-libraries}

# Clean the environment and load libraries ############################

rm(list=ls())

source('./scripts/utils/load_all_libraries.R')

```

# Load the data and set flags

(code hidden)

```{r load-transform-tt-data}

reportBF = function(x, digits){
        round(as.numeric(as.vector(x)), digits)
}

plot_dep_var <- 'post_pre_diff'

qc_filter <- T
print(paste0('QC filter? ', qc_filter))


experiment <- c('experiment_1') # experiment_1 is the main experiment, pilot_3 is the last pilot

print(paste0('Which pilot paradigm? ', experiment))

source('./scripts/utils/load_transform_tt_data.R') # loads the triplet task
source('./scripts/utils/load_transform_exp_data.R') # loads the exposure task

source('./scripts/utils/summary_stats_for_various_factors.R') #this will calculate various summary statistics, grouped by different factors (and their combinations) like triplet easiness, triplet location, template, etc

# Flags and settings

chose_sparse_color  <- 'blue'
chose_highdim_color <- 'green'
accuracy_color      <- 'yellow'

# Show the basic table
tt_long %>%
        filter(trial_index == 1,session == 1,trial_stage == 'pre_exposure') %>%
        group_by(counterbalancing,
                 prolific_id) %>%
        summarise(n = n()) %>%
        knitr::kable(caption = 'Participants and counterbalancing') %>%
        kable_styling(bootstrap_options = "striped")

```

# Middle triplets, against 0

All types of middle triplets, symmetric and asymmetric

## Plot:

```{r mid-triplets-vs-0-plot}

ylimits <- c(-0.2,0.2)

fig1 <- tt_part_sum_stats_triplet_location %>%
        filter(triplet_location == 'across_density_regions',
               dep_var_type == 'post_pre_diff') %>%
        ggplot(aes(x='All participants',
                   y=mean_chose_towards_sparse)) +
        geom_violin(fill = chose_sparse_color,
                    alpha = 0.2) +
        geom_boxplot(width = 0.15,
                     outlier.shape = '',
                     fatten = 4) +
        geom_jitter(width = 0.05,
                    height = 0,
                    alpha = 0.3) +
        stat_summary(fun = mean,
                     color = 'red') + geom_hline(yintercept = 0, linetype = 'dashed') + 
        stat_summary(fun.data = mean_cl_normal,
                     geom = "errorbar",
                     size=0.5,
                     width=0.1,
                     color='red') 

fig2 <- tt_part_sum_stats_triplet_location %>%
        filter(triplet_location == 'across_density_regions',
               dep_var_type == 'post_pre_diff') %>%
        ggplot(aes(x=counterbalancing,
                   y=mean_chose_towards_sparse)) +
        geom_violin(fill = chose_sparse_color,
                    alpha = 0.2) +
        geom_boxplot(width = 0.15,
                     outlier.shape = '',
                     fatten = 4) +
        geom_jitter(width = 0.05,
                    height = 0,
                    alpha = 0.3) +
        stat_summary(fun = mean,
                     color = 'red') + geom_hline(yintercept = 0, linetype = 'dashed') + 
        stat_summary(fun.data = mean_cl_normal,
                     geom = "errorbar",
                     size=0.5,
                     width=0.1,
                     color='red')

grid.arrange(fig1,fig2,
             nrow = 1,
             top = 'Post minus pre')

```

## Bayes Factors

```{r mid-triplets-vs-0-effect-size}

tbl_effsize <- tt_part_sum_stats_triplet_location %>%
        filter(dep_var_type == 'post_pre_diff',
               triplet_location == 'across_density_regions') %>%
        cohens_d(mean_chose_towards_sparse ~ 1,
                 mu = 0,
                 hedges.correction = FALSE)

```

```{r mid-triplets-vs-0-bayes-factor}

bf_data <- tt_part_sum_stats_triplet_location %>%
        filter(dep_var_type == 'post_pre_diff',
               triplet_location == 'across_density_regions') %>%
        droplevels() %>% 
        select(mean_chose_towards_sparse) %>% .[[1]]

null_interval <- c(0,Inf)

bf <- reportBF(ttestBF(
        bf_data,
        nullInterval = null_interval
)[1],4)

```

```{r mid-triplets-vs-0-cb-groups}

bf_data_dense_left <- tt_part_sum_stats_triplet_location %>%
        filter(dep_var_type == 'post_pre_diff',
               triplet_location == 'across_density_regions',
               counterbalancing == 'dense_left') %>%
        droplevels() %>% 
        select(mean_chose_towards_sparse) %>% .[[1]]

bf_data_dense_right <- tt_part_sum_stats_triplet_location %>%
        filter(dep_var_type == 'post_pre_diff',
               triplet_location == 'across_density_regions',
               counterbalancing == 'dense_right') %>%
        droplevels() %>% 
        select(mean_chose_towards_sparse) %>% .[[1]]

null_interval <- c(0,Inf)

bf_compare_cb <- reportBF(ttestBF(
        bf_data_dense_left,bf_data_dense_right,
)[1],4)

bf_dense_left <- reportBF(ttestBF(
        bf_data_dense_left,
        nullInterval = null_interval
)[1],4)

bf_dense_right <- reportBF(ttestBF(
        bf_data_dense_right,
        nullInterval = null_interval
)[1],4)


```


# Harderst middle triplets vs 0

The easy-0 middle triplets, reported in the thesis.

## Plot

```{r mid-hardest-triplets-vs-0-plot}

ylimits <- c(-0.2,0.2)

fig1 <- tt_part_sum_stats_triplet_location_easiness %>%
        filter(triplet_location == 'across_density_regions',
               dep_var_type == 'post_pre_diff',
               triplet_easiness == 0) %>%
        ggplot(aes(x='All participants',
                   y=mean_chose_towards_sparse)) +
        geom_violin(fill = chose_sparse_color,
                    alpha = 0.2,
                    width = 0.5) +
        geom_boxplot(width = 0.15,
                     outlier.shape = '',
                     fatten = 4) +
        geom_jitter(width = 0.1,
                    height = 0,
                    alpha = 0.2) +
        stat_summary(fun = mean,
                     color = 'red') + geom_hline(yintercept = 0, linetype = 'dashed') + 
        stat_summary(fun.data = mean_cl_normal,
                     geom = "errorbar",
                     size=0.5,
                     width=0.1,
                     color='red') +
        ylab('p(chose-low-density)') +
        xlab('') +
        ggtitle('All participants') + 
        theme(plot.title = element_text(hjust = 0.5)) +
        theme(plot.title = element_text(size = 10)) 

fig2 <- tt_part_sum_stats_triplet_location_easiness %>%
        filter(triplet_location == 'across_density_regions',
               dep_var_type == 'post_pre_diff',
               triplet_easiness == 0) %>%
        ggplot(aes(x=counterbalancing,
                   y=mean_chose_towards_sparse)) +
        geom_violin(fill = chose_sparse_color,
                    alpha = 0.2,
                    width = 0.7) +
        geom_boxplot(width = 0.15,
                     outlier.shape = '',
                     fatten = 4) +
        geom_jitter(width = 0.1,
                    height = 0,
                    alpha = 0.2) +
        stat_summary(fun = mean,
                     color = 'red') + 
        geom_hline(yintercept = 0, linetype = 'dashed') + 
        stat_summary(fun.data = mean_cl_normal,
                     geom = "errorbar",
                     size=0.5,
                     width=0.1,
                     color='red') +
        ylab('p(chose-low-density)') +
        xlab('') +
        ggtitle('Each counterbalancing group') + 
        theme(plot.title = element_text(hjust = 0.5)) +
        theme(plot.title = element_text(size = 10)) + 
        scale_x_discrete(labels = c('Dense-Left','Dense-Right'))

p <- grid.arrange(fig1,fig2,
             nrow = 1,
             top = 'Symmetric middle triplets')

ggsave(filename = 'middle_symmetric_p_chose_low_density.png', plot = p, path = './results/plots/', width = 5, height = 4, device='png', dpi=300)

```

## Bayes factors

```{r mid-hardest-triplets-vs-0-effect-size}

tbl_effsize <- tt_part_sum_stats_triplet_location_easiness %>%
        filter(dep_var_type == 'post_pre_diff',
               triplet_location == 'across_density_regions',
               triplet_easiness == 0) %>%
        cohens_d(mean_chose_towards_sparse ~ 1,
                 mu = 0,
                 hedges.correction = FALSE)

```

```{r mid-hardest-triplets-vs-0-bayes-factor}

bf_data <- tt_part_sum_stats_triplet_location_easiness %>%
        filter(dep_var_type == 'post_pre_diff',
               triplet_location == 'across_density_regions',
               triplet_easiness == 0) %>%
        droplevels() %>% 
        select(mean_chose_towards_sparse) %>% .[[1]]

null_interval <- c(0,Inf)

bf <- reportBF(ttestBF(
        bf_data,
        nullInterval = null_interval
)[1],4)

```

```{r mid-harderst-triplets-vs-0-cb-groups}

bf_data_dense_left <- tt_part_sum_stats_triplet_location_easiness %>%
        filter(dep_var_type == 'post_pre_diff',
               triplet_location == 'across_density_regions',
               counterbalancing == 'dense_left',
               triplet_easiness == 0) %>%
        droplevels() %>% 
        select(mean_chose_towards_sparse) %>% .[[1]]

bf_data_dense_right <- tt_part_sum_stats_triplet_location_easiness %>%
        filter(dep_var_type == 'post_pre_diff',
               triplet_location == 'across_density_regions',
               counterbalancing == 'dense_right',
               triplet_easiness == 0) %>%
        droplevels() %>% 
        select(mean_chose_towards_sparse) %>% .[[1]]

null_interval <- c(0,Inf)

bf_compare_cb <- reportBF(ttestBF(
        bf_data_dense_left,bf_data_dense_right,
)[1],4)

bf_dense_left <- reportBF(ttestBF(
        bf_data_dense_left,
        nullInterval = null_interval
)[1],4)

bf_dense_right <- reportBF(ttestBF(
        bf_data_dense_right,
        nullInterval = null_interval
)[1],4)


```


# Regional analysis: across minus other areas

## Violin plots

```{r triplet-location-differences-easiness-levels, fig.width=9, fig.height=7, warning=F}

x_font_size <- 10
x_font_angle <- 0

# Now plot this
fig1 <- tt_part_sum_stats_triplet_location_easiness_differences %>%
        filter(dep_var_type == plot_dep_var,
               measure_type == 'chose_towards_sparse',
               triplet_easiness == 0,
               difference_type == 'across_minus_avg_dense_sparse') %>% 
        ggplot(aes(x='All participants',
                   y=difference_value)) +
        geom_violin(fill = chose_sparse_color,alpha = 0.2,
                    width = 0.6) +
        geom_boxplot(width=0.2,
                     outlier.shape = '', fatten = 4) +
        geom_jitter(width = 0.05,
                    height = 0,
                    alpha = 0.3) + 
        # geom_line(aes(group=prolific_id),
        #           alpha = 0.2) +  
        stat_summary(fun = mean,
                     color = 'red') + 
        stat_summary(fun.data = mean_cl_normal,
             geom = "errorbar",
             size=0.5,
             width=0.1,
             color='red') + 
        geom_hline(yintercept = 0, linetype = 'dashed') +      
        theme(text = element_text(size=x_font_size)) + 
        theme(axis.text.x = element_text(angle = x_font_angle)) +
        ylab('Middle-avg(high+low) diff score') +
        xlab('') +
        ggtitle('All participants') + 
        theme(plot.title = element_text(hjust = 0.5)) +
        theme(plot.title = element_text(size = 10)) +
        theme(axis.title.y = element_text(size = 7)) 

# + 
#         ggtitle(paste0(plot_dep_var, '. chose towards sparse. Diff scores'))

fig2 <- tt_part_sum_stats_triplet_location_easiness_differences %>%
        filter(dep_var_type == plot_dep_var,
               measure_type == 'chose_towards_sparse',
               triplet_easiness == 0,
               difference_type == 'across_minus_avg_dense_sparse') %>% 
        ggplot(aes(x=counterbalancing,
                   y=difference_value)) +
        geom_violin(fill = chose_sparse_color,alpha = 0.2,
                    width = 0.6) +
        geom_boxplot(width=0.2,
                     outlier.shape = '', fatten = 4) +
        geom_jitter(width = 0.05,
                    height = 0,
                    alpha = 0.3) + 
        # geom_line(aes(group=prolific_id),
        #           alpha = 0.2) +  
        stat_summary(fun = mean,
                     color = 'red') + 
        stat_summary(fun.data = mean_cl_normal,
             geom = "errorbar",
             size=0.5,
             width=0.1,
             color='red') + 
        geom_hline(yintercept = 0, linetype = 'dashed') +      
        theme(text = element_text(size=x_font_size)) + 
        theme(axis.text.x = element_text(angle = x_font_angle)) + 
        # facet_wrap(~counterbalancing)  +
        ylab('') +
        xlab('') +
        ggtitle('Each counterbalancing group') + 
        theme(plot.title = element_text(hjust = 0.5)) +
        theme(plot.title = element_text(size = 10)) 

# +
#         ggtitle(paste0(plot_dep_var, '. chose towards sparse. Diff scores'))

p <- grid.arrange(fig1,fig2,
             nrow = 1,
             widths = 1:2,
             top = 'Within-template differences')

# ggsave(filename = 'within_template_diff.png', plot = p, path = './results/plots/', width = 5, height = 3, device='png', dpi=300)

```

## Bayes factors:

```{r bf-regional-analysis}
data_for_bf_regional_analysis <- tt_part_sum_stats_triplet_location_easiness_differences %>%
        filter(dep_var_type == plot_dep_var,
               measure_type == 'chose_towards_sparse',
               triplet_easiness == 0,
               difference_type == 'across_minus_avg_dense_sparse') %>% 
        select(difference_value) %>% .[[1]]

null_interval <- c(0,Inf)

bf_regional_analysis <- reportBF(ttestBF(
        data_for_bf_regional_analysis,
        nullInterval = null_interval
)[1],4)

1/bf_regional_analysis

bf_regional_analysis_cb_groups <- tt_part_sum_stats_triplet_location_easiness_differences %>%
        filter(dep_var_type == plot_dep_var,
               measure_type == 'chose_towards_sparse',
               triplet_easiness == 0,
               difference_type == 'across_minus_avg_dense_sparse') %>% 
        group_by(counterbalancing) %>%
        
        summarise(bf = reportBF(ttestBF(cur_data()$difference_value,
                                        nullInterval = null_interval)[1],4)) %>%
        ungroup()

```


# Exposure same-different task:

```{r exposure-psychometric-curve, fig.width=10, fig.height=6}

n_same_resp <- 
        exp_long %>%
        group_by(prolific_id,
                 dist_abs_from_prev,
                 response,
                 .drop=FALSE) %>% 
        summarise(n = n()) %>%
        ungroup() %>%
        filter(response == 'q')

n_tot_resp <- 
        exp_long %>%
        group_by(prolific_id,
                 dist_abs_from_prev) %>%
        summarise(n = n()) %>%
        ungroup()

same_resp_table <- 
        merge(n_same_resp,
              n_tot_resp,
              by=c('prolific_id','dist_abs_from_prev')) %>%
        mutate(avg_same_resp = n.x/n.y) %>% 
        ungroup()

p <- same_resp_table %>%
        filter(!is.na(dist_abs_from_prev)) %>%
        mutate(dist_abs_from_prev = as.numeric(as.character(dist_abs_from_prev))) %>%
        ggplot(aes(x=dist_abs_from_prev,y=avg_same_resp)) +
        # geom_point(size=0.7,
        #            alpha = 0.2) +
        geom_jitter(size = 0.7,
                    alpha = 0.2,
                    height = 0,
                    width = 0.2) +
        # geom_smooth(size=1) +
        stat_summary(fun='mean',
                     geom='line',
                     size=1,
                     color = 'red') +
        stat_summary(fun='mean',
                     geom='point',
                     size=2,
                     color = 'red') +        
        scale_y_continuous(breaks=seq(0,1,0.05)) +
        scale_x_continuous(breaks=seq(0,80,2)) +
        ylab('Confusability') +
        xlab('1-back distance in generative space') + 
        theme_classic() +
        theme(axis.text.x = element_text(angle = 90),
              legend.position = '') +
        geom_hline(yintercept = 1-0.75,linetype='dashed') +
        geom_hline(yintercept = 1-0.5,linetype='dashed') +
        # stat_summary(aes(x=dist_abs_from_prev,y=n.y),
        #              fun='mean',
        #              geom='line',
        #              size=1) + 
        ggtitle('Exposure task psychometric curves') +
        theme(plot.title = element_text(hjust = 0.5))

print(p)

ggsave(filename = 'exposure_psychometric.png', plot = p, path = './results/plots/', width = 8, height = 4, device='png', dpi=300)

same_resp_table %>%
  group_by(prolific_id,
           dist_abs_from_prev) %>%
  summarise(n = n())


```
