---
title: "experiments_analysis_exposure"
output:
  html_document:
    number_sections: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r load-libraries}

# Clean the environment and load libraries ############################

rm(list=ls())

source('./scripts/utils/load_all_libraries.R')

```

```{r load-transform-data}

qc_filter <- T
print(paste0('QC filter? ', qc_filter))

experiment <- c('experiment_1')
print(paste0('Which experiment? ', experiment))

source('./scripts/utils/load_transform_exp_data.R')


```

```{r n-same-diff-responses, fig.width=10}


n_same_resp <- 
        exp_long %>%
        group_by(prolific_id,
                 dist_abs_from_prev,
                 response,
                 .drop=FALSE) %>% 
        summarise(n = n()) %>%
        ungroup() %>%
        filter(response == 'q')


n_tot_resp <- 
        exp_long %>%
        group_by(prolific_id,
                 dist_abs_from_prev) %>%
        summarise(n = n()) %>%
        ungroup()

same_resp_table <- 
        merge(n_same_resp,
              n_tot_resp,
              by=c('prolific_id','dist_abs_from_prev')) %>%
        mutate(avg_same_resp = n.x*100/n.y) %>% 
        ungroup()

same_resp_table %>%
        filter(!is.na(dist_abs_from_prev)) %>%
        mutate(dist_abs_from_prev = as.numeric(as.character(dist_abs_from_prev))) %>%
        ggplot(aes(x=dist_abs_from_prev,y=avg_same_resp)) +
        geom_point(size=0.5,
                   alpha = 0.3) +
        # geom_line(size=0.5, aes(group=prolific_id,color=prolific_id)) +
        # geom_point(size=2, aes(group = prolific_id,color = prolific_id)) + 
        # geom_line(size=1, aes(group = prolific_id,color = prolific_id)) + 
        geom_smooth(size=1) +
        stat_summary(fun='mean',
                     geom='line',
                     size=1.5,
                     color = 'red',
                     linetype = 'dashed'
                     ) +
        # geom_line(aes(x=dist_abs_from_prev,y=n.y),color='red') +
        scale_y_continuous(breaks=seq(0,100,5)) +
        scale_x_continuous(breaks=seq(0,80,1)) +
        ylab('% "Same" response') +
        xlab('Unit distance from previous') + 
        theme_classic() +
        theme(axis.text.x = element_text(angle = 90),
              legend.position = '') +
        geom_hline(yintercept = 100-75,linetype='dashed') +
        geom_hline(yintercept = 100-50,linetype='dashed') +
        stat_summary(aes(x=dist_abs_from_prev,y=n.y),
                     fun='mean',
                     geom='line',
                     size=1) + 
        ggtitle('exposure psychometric curves')

same_resp_table %>%
  group_by(prolific_id,
           dist_abs_from_prev) %>%
  summarise(n = n())


```

```{r accuracy-same-diff}

# exp_long %>%
#         filter(trial_index != 2) %>% 
#         mutate(correct = as.numeric(correct)) %>%
#         reorder_levels(correct_response,order = c('q','p')) %>% 
#         group_by(prolific_id,
#                  correct_response) %>%
#         get_summary_stats(correct,type='mean_sd') %>% 
#         ggplot(aes(x=correct_response,y=mean)) +
#         geom_violin(width=0.2) +
#         geom_point() +
#         geom_line(aes(group=prolific_id,
#                       color=prolific_id)) +
#         theme(legend.position = '') + 
#         ylab('Accuracy') + 
#         ggtitle('Accuracy by trial type: Same vs Diff')


```

# Analyze "same" response for each pair of items

```{r exp-long-add-column}

exp_long <- exp_long %>%
        mutate(stim_val_density = case_when(
                counterbalancing == 'dense_left' & stim_val %in% seq(0,69) ~ 'high',
                counterbalancing == 'dense_left' & stim_val %in% seq(70,110) ~ 'low',
                counterbalancing == 'dense_right' & stim_val %in% seq(0,69) ~ 'low',
                counterbalancing == 'dense_right' & stim_val %in% seq(70,110) ~ 'high',
                TRUE ~ as.character(NA)
        ),
        prev_stim_val_density = case_when(
                counterbalancing == 'dense_left' & prev_stim_val %in% seq(0,69) ~ 'high',
                counterbalancing == 'dense_left' & prev_stim_val %in% seq(70,110) ~ 'low',
                counterbalancing == 'dense_right' & prev_stim_val %in% seq(0,69) ~ 'low',
                counterbalancing == 'dense_right' & prev_stim_val %in% seq(70,110) ~ 'high',
                TRUE ~ as.character(NA)
        ))

```

## Psych curve for high vs low denstiy stimulis

```{r psych-curve-for-high-vs-low-density-stimuli}

which_distances <- seq(8,88, by = 8)
which_counterbalancing <- c('dense_right','dense_left')
which_stimuli <- seq(30,110, by = 2)

n_tot_same_trials <- exp_long %>%
        select(counterbalancing,
               prolific_id,
               session,
               response,
               # stim_val,
               stim_val_density,
               dist_abs_from_prev) %>%
        filter(!is.na(response),
               counterbalancing %in% which_counterbalancing,
               dist_abs_from_prev %in% which_distances,
               # stim_val %in% which_stimuli
               ) %>%
        count(counterbalancing,
              prolific_id,
              session,
              stim_val_density,
              dist_abs_from_prev,
              .drop = F) %>%
        rename(n_total = n)

n_same_resp_same_trials <- exp_long %>%
        filter(!is.na(response),
               counterbalancing %in% which_counterbalancing,
               dist_abs_from_prev %in% which_distances,
               # stim_val %in% which_stimuli
               ) %>%
        select(counterbalancing,
               prolific_id,
               session,
               response,
               # stim_val,
               stim_val_density,
               dist_abs_from_prev) %>%        
        count(counterbalancing,
              prolific_id,
              session,
              stim_val_density,
              response,
              dist_abs_from_prev,
              .drop = F) %>% 
        rename(n_resp = n) %>% 
        filter(response == 'q')

same_resp_table_same_trials <- 
        merge(n_same_resp_same_trials,
              n_tot_same_trials,
              by=c('counterbalancing','prolific_id','stim_val_density','session','dist_abs_from_prev')) %>% 
        mutate(prob_same_resp = n_resp/n_total) %>% 
        ungroup()




```


## Perc "same" response by session, density, counterbalancing

### On "same" trials 

```{r same-trials, fig.height=3, fig.width=3}

# For each exemplar, whats the histogram of distances that we have 
which_distances <- seq(0,0, by = 0)
which_counterbalancing <- c('dense_right','dense_left')
which_stimuli <- seq(30,110, by = 2)

n_tot_same_trials <- exp_long %>%
        select(counterbalancing,
               prolific_id,
               session,
               response,
               stim_val,
               stim_val_density,
               dist_abs_from_prev) %>%
        filter(!is.na(response),
               counterbalancing %in% which_counterbalancing,
               dist_abs_from_prev %in% which_distances,
               stim_val %in% which_stimuli) %>%
        count(counterbalancing,
              prolific_id,
              session,
              stim_val_density,
              .drop = F) %>%
        rename(n_total = n)

n_same_resp_same_trials <- exp_long %>%
        filter(!is.na(response),
               counterbalancing %in% which_counterbalancing,
               dist_abs_from_prev %in% which_distances,
               stim_val %in% which_stimuli) %>%
        select(counterbalancing,
               prolific_id,
               session,
               response,
               stim_val,
               stim_val_density,
               dist_abs_from_prev) %>%        
        count(counterbalancing,
              prolific_id,
              session,
              stim_val_density,
              response,
              .drop = F) %>% 
        rename(n_resp = n) %>% 
        filter(response == 'q')

same_resp_table_same_trials <- 
        merge(n_same_resp_same_trials,
              n_tot_same_trials,
              by=c('counterbalancing','prolific_id','stim_val_density','session')) %>% 
        mutate(prob_same_resp = n_resp/n_total) %>% 
        ungroup()

plot_which_session <- c(4,5)

p <- same_resp_table_same_trials %>%
        filter(session %in% plot_which_session) %>%
        group_by(counterbalancing,
                 prolific_id,
                 stim_val_density) %>%
        summarise(prob_same_resp = mean(prob_same_resp)) %>% 
        ggplot(aes(x=stim_val_density,
                   y=prob_same_resp)) +
        geom_violin(width = 1) +
        geom_boxplot(width = 0.1,
                     fatten = 5) +
        geom_point(alpha = 0.1) +
        geom_line(aes(group=prolific_id),
                  alpha=0.05) +
        stat_summary(fun=mean,
                 color='red',
                 size = 0.6) +
        ggtitle(paste0('True same trials')) +
        theme(plot.title = element_text(hjust = 0.5)) +
        # theme(plot.title = element_text(size = 15)) +
        ylab('Prob. Respond "same"') +
        xlab('') +
        scale_x_discrete(labels = c('High density','Low density'))

print(p)

ggsave(filename = 'same_trials_same_response.png', plot = p, path = './results/plots/', width = 3, height = 3, device='png', dpi=300)

```

### Now for "different" trials 

```{r diff-trials, fig.height=3, fig.width=3}

# For each exemplar, whats the histogram of distances that we have 
which_distances <- seq(8,80, by = 8)
which_counterbalancing <- c('dense_right','dense_left')
which_stimuli <- seq(30,110, by = 2)

n_tot_diff_trials <- exp_long %>%
        select(counterbalancing,
               prolific_id,
               session,
               response,
               stim_val,
               stim_val_density,
               dist_abs_from_prev) %>%
        filter(!is.na(response),
               counterbalancing %in% which_counterbalancing,
               dist_abs_from_prev %in% which_distances,
               stim_val %in% which_stimuli) %>%
        count(counterbalancing,
              prolific_id,
              session,
              stim_val_density,
              .drop = F) %>%
        rename(n_total = n)

n_same_resp_diff_trials <- exp_long %>%
        filter(!is.na(response),
               counterbalancing %in% which_counterbalancing,
               dist_abs_from_prev %in% which_distances,
               stim_val %in% which_stimuli) %>%
        select(counterbalancing,
               prolific_id,
               session,
               response,
               stim_val,
               stim_val_density,
               dist_abs_from_prev) %>%        
        count(counterbalancing,
              prolific_id,
              session,
              stim_val_density,
              response,
              .drop = F) %>% 
        rename(n_resp = n) %>% 
        filter(response == 'q')

same_resp_table_diff_trials <- 
        merge(n_same_resp_diff_trials,
              n_tot_diff_trials,
              by=c('counterbalancing','prolific_id','stim_val_density','session')) %>% 
        mutate(prob_same_resp = n_resp/n_total) %>% 
        ungroup()

plot_which_session <- c(1)

p <- same_resp_table_diff_trials %>%
        filter(session %in% plot_which_session) %>%
        group_by(counterbalancing,
                 prolific_id,
                 stim_val_density) %>%
        summarise(prob_same_resp = mean(prob_same_resp)) %>% 
        ggplot(aes(x=stim_val_density,
                   y=prob_same_resp)) +
        geom_violin() +
        geom_boxplot(width = 0.1,
                     fatten = 5) +
        geom_point(alpha = 0.1) +
        geom_line(aes(group=prolific_id),
                  alpha=0.05) +
        stat_summary(fun=mean,
                 color='red',
                 size = 0.6) +
        # ggtitle(paste0('Diff trials: % Same response in session(s) ', paste(plot_which_session, sep = '_', collapse = '_')))
        ggtitle(paste0('True different trials')) +
        theme(plot.title = element_text(hjust = 0.5)) +
        # theme(plot.title = element_text(size = 15)) +
        ylab('Prob. Respond "same"') +
        xlab('') +
        scale_x_discrete(labels = c('High density','Low density'))
print(p)
ggsave(filename = 'diff_trials_same_response.png', plot = p, path = './results/plots/', width = 3, height = 3, device='png', dpi=300)

```


## Accuracy by session, density, coutnerbalancing

```{r acc-by-session-density-counterbalancing}


which_distances <- seq(0,80, by = 8)
which_counterbalancing <- c('dense_right','dense_left')
which_stimuli <- seq(30,110, by = 2)

n_tot_correct_trials <- exp_long %>%
        select(counterbalancing,
               prolific_id,
               session,
               correct,
               stim_val_density,
               dist_abs_from_prev) %>%
        filter(!is.na(correct),
               counterbalancing %in% which_counterbalancing,
               dist_abs_from_prev %in% which_distances) %>% 
        droplevels() %>%
        count(counterbalancing,
              prolific_id,
              session,
              stim_val_density,
              correct,
              .drop = F) 

plot_which_session <- c(4,5)

n_tot_correct_trials %>%
        filter(session %in% plot_which_session) %>%
        group_by(counterbalancing,
                 prolific_id,
                 stim_val_density) %>%
        summarise(mean_correct = mean(as.numeric(correct))) %>% 
        ggplot(aes(x=stim_val_density,
                   y=mean_correct)) +
        geom_violin() +
        geom_boxplot(width = 0.1,
                     fatten = 5) +
        geom_jitter(height = 0,
                    width = 0.1,
                    alpha = 0.1) +
        geom_line(aes(group=prolific_id),
                  alpha=0.2) +
        # geom_boxplot(aes(group=stim_val)) +
        stat_summary(fun=mean,
                 color='red',
                 size = 1) +
        facet_grid(~counterbalancing) +
        ggtitle(paste0('% Correct in session(s) ', paste(plot_which_session, sep = '_', collapse = '_')))

```



```{r analyze-same-diff-response-probability, fig.width=15, fig.height=6}

# For each exemplar, whats the histogram of distances that we have 
which_distances <- seq(8,80, by = 8)
which_counterbalancing <- c('dense_right','dense_left')

# exp_long <-
# exp_long %>%
#         mutate(stim_val = case_when(
#                 counterbalancing == 'dense_right' ~ as.numeric(stim_val),
#                 TRUE ~ 2*70 - as.numeric(stim_val)
#         )) %>%
#         mutate(stim_val = as.factor(stim_val),
#                counterbalancing = 'dense_right')

n_tot_resp2 <- exp_long %>%
        filter(!is.na(response),
               counterbalancing %in% which_counterbalancing) %>% 
        select(counterbalancing,
               prolific_id,
               response,
               stim_val,
               dist_abs_from_prev) %>%        
        filter(
                # prolific_id == prolific_id[1],
               dist_abs_from_prev %in% which_distances) %>% 
        count(counterbalancing,
              prolific_id,
              stim_val,
              .drop = F) %>% 
        rename(n_total = n)

n_same_resp2 <- exp_long %>%
        filter(!is.na(response),
               counterbalancing %in% which_counterbalancing) %>%
        select(counterbalancing,
               prolific_id,
               response,
               stim_val,
               dist_abs_from_prev) %>%        
        filter(
                # prolific_id == prolific_id[1],
               dist_abs_from_prev %in% which_distances) %>%
        count(counterbalancing,
              prolific_id,
              stim_val,
              response,
              .drop = F) %>% 
        rename(n_resp = n) %>% 
        filter(response == 'q')

same_resp_table2 <- 
        merge(n_same_resp2,
              n_tot_resp2,
              by=c('counterbalancing','prolific_id','stim_val')) %>% 
        mutate(perc_same_resp = n_resp*100/n_total) %>% 
        ungroup()

same_resp_table2 %>%
        filter(!stim_val %in% seq(30,110, by = 8)) %>%
       ggplot(aes(x=reorder(stim_val,stim_val),
                   y=perc_same_resp,
                   group=stim_val)) +
        geom_violin(aes(group=stim_val)) +
        geom_jitter(height = 0,
                    width = 0.1,
                    alpha = 0.1) +
        # geom_boxplot(aes(group=stim_val)) +
        stat_summary(fun=mean,
                 color='red',
                 size = 1) +
        facet_wrap(~counterbalancing) +
        ggtitle('% Same response')

same_resp_table2 %>%
       ggplot(aes(x=reorder(stim_val,stim_val),
                   y=n_total,
                   group=stim_val)) +
        geom_violin(aes(group=stim_val)) +
        geom_jitter(height = 0,
                    width = 0.1,
                    alpha = 0.1) +
        # geom_boxplot(aes(group=stim_val)) +
        stat_summary(fun=mean,
                 color='blue',
                 size=1) +
        facet_wrap(~counterbalancing) +
        ggtitle('Count of trials')

```











