---
title: "TT choose sparse"
output:
  html_document:
    number_sections: false
    
knit: (function(input, ...) {
    rmarkdown::render(
      input,
      knit_root_dir = rprojroot::find_rstudio_root_file(),
      output_file = paste0(
      rprojroot::find_rstudio_root_file(),
      '/results/pilots/',
      'pilot_chose_sparse_paradigm_2_3_qc_filtered_',Sys.Date(),'.html'

      ),
      envir = globalenv()
    )
  })
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

# Suppress summarise info
options(dplyr.summarise.inform = FALSE)

```

```{r load-libraries}

# Clean the environment and load libraries ############################

rm(list=ls())

source('./scripts/utils/load_all_libraries.R')

```

# Load the data and set flags

(code hidden)

```{r load-transform-tt-data}

qc_filter <- T
print(paste0('QC filter? ', qc_filter))


which_paradigm <- c(3)

print(paste0('Which pilot paradigm? ', which_paradigm))

source('./scripts/utils/load_transform_tt_data.R')
source('./scripts/utils/summary_stats_for_various_factors.R')

# Flags and settings

chose_sparse_color  <- 'blue'
chose_highdim_color <- 'green'
accuracy_color      <- 'yellow'

# Show the basic table
tt_long %>%
        filter(trial_index == 1,session == 1,trial_stage == 'pre_exposure') %>%
        group_by(counterbalancing,
                 prolific_id) %>%
        summarise(n = n()) %>%
        knitr::kable(caption = 'Participants and counterbalancing') %>%
        kable_styling(bootstrap_options = "striped")

```

# Over all trials, pre post and post-pre

```{r all-trials, fig.width=12, fig.height=3, warning=F}

#  
fig3 <- tt_part_sum_stats %>%
        #filter(dep_var_type == 'post_pre_diff') %>% 
        ggplot(aes(x=dep_var_type,
                   y=mean_chose_towards_sparse)) +
        geom_violin(fill = chose_sparse_color,alpha = 0.2) +
        geom_boxplot(width=0.2,
                     outlier.shape = '', 
                     fatten = 6) +
        geom_jitter(width = 0.05,
                    height = 0,
                    alpha = 0.3) + 
        geom_line(aes(group=prolific_id),
                  alpha = 0.2) +     
        stat_summary(fun = mean,
                     color = 'red') + 
        stat_summary(fun.data = mean_cl_normal,
             geom = "errorbar",
             size=1,
             width=0.1,
             color='red') +         
        geom_hline(yintercept = c(0,0.5), linetype = 'dashed') +         
        ggtitle('chose towards sparse')

fig4 <- tt_part_sum_stats %>%
        #filter(dep_var_type == 'post_pre_diff') %>% 
        ggplot(aes(x=dep_var_type,
                   y=mean_chose_towards_sparse)) +
        geom_violin(fill = chose_sparse_color,alpha = 0.2) +
        geom_boxplot(width=0.15,
                     outlier.shape = '',
                     fatten = 6) +
        geom_jitter(width = 0.05,
                    height = 0,
                    alpha = 0.3) +
        geom_line(aes(group=prolific_id),
                  alpha = 0.2) +    
        stat_summary(fun = mean,
                     color = 'red') + 
        stat_summary(fun.data = mean_cl_normal,
             geom = "errorbar",
             size=1,
             width=0.1,
             color='red') +         
        geom_hline(yintercept = c(0,0.5), linetype = 'dashed') +         
        facet_wrap(~counterbalancing)

grid.arrange(fig3,fig4,
             nrow = 1,
             widths = 1:2)
             
```

```{r triplet-location, fig.width=12, fig.height=7, warning=F}
x_font_size <- 10

fig3 <- tt_part_sum_stats_triplet_location %>%
        # filter(dep_var_type == plot_dep_var) %>% 
        ggplot(aes(x=triplet_location,
                   y=mean_chose_towards_sparse)) +
        geom_violin(fill = chose_sparse_color,alpha = 0.2) +
        geom_boxplot(width=0.2,
                     outlier.shape = '', fatten = 4) +
        geom_jitter(width = 0.05,
                    height = 0,
                    alpha = 0.3) + 
        geom_line(aes(group=prolific_id),
                  alpha = 0.2) +     
        stat_summary(fun = mean,
                     color = 'red') + 
        stat_summary(fun.data = mean_cl_normal,
             geom = "errorbar",
             size=1,
             width=0.1,
             color='red') +          
        geom_hline(yintercept = c(0,0.5), linetype = 'dashed') +   
        theme(text = element_text(size=x_font_size)) + 
        ggtitle(paste0('All stages','; chose towards sparse')) +
        facet_wrap(~dep_var_type, ncol = 1, strip.position = 'right')

fig4 <- tt_part_sum_stats_triplet_location %>%
        # filter(dep_var_type == plot_dep_var) %>% 
        ggplot(aes(x=triplet_location,
                   y=mean_chose_towards_sparse)) +
        geom_violin(fill = chose_sparse_color,alpha = 0.2) +
        geom_boxplot(width=0.15,
                     outlier.shape = '', fatten = 4) +
        geom_jitter(width = 0.05,
                    height = 0,
                    alpha = 0.3) +
        geom_line(aes(group=prolific_id),
                  alpha = 0.2) +    
        stat_summary(fun = mean,
                     color = 'red') + 
        stat_summary(fun.data = mean_cl_normal,
             geom = "errorbar",
             size=1,
             width=0.1,
             color='red') +          
        geom_hline(yintercept = c(0,0.5), linetype = 'dashed') +      
        theme(text = element_text(size=x_font_size)) + 
        facet_grid(dep_var_type~counterbalancing)

grid.arrange(fig3,fig4,
             nrow = 1,
             widths = 1:2)

```


```{r which-dep-var}

# What to plot on the y axis

plot_dep_var <- 'post_pre_diff'


if (plot_dep_var != 'post_pre_diff'){
        y_intercept <- 0.5        
} else {
        y_intercept <- 0
}

```

# Sorted x axis by dep var

```{r sorted-plot-chose-sparse, fig.width=13, fig.height=18}

# For sorted data
fig1 <- tt_long_post_pre_and_diff %>%
        filter(dep_var_type == plot_dep_var) %>% 
        ggplot(aes(x=reorder(triplet_unique_name,-chose_towards_sparse_avg_across_reps),
                   y=chose_towards_sparse_avg_across_reps)) +
        geom_boxplot(fatten = 6, aes(color=curve_type)) + 
        stat_summary(fun=mean,
                     geom = 'point',
                     size = 5,
                     color="black",
                     aes(shape = triplet_easiness)) + 
        geom_hline(yintercept = y_intercept, linetype = 'dashed') +
        theme(axis.text.x = element_text(angle = 90),
              legend.position = 'top') +
        ylab(paste0(plot_dep_var, '; chose sparse')) +
        xlab('Individual Triplets') +
        ggtitle('All counterbalancing groups')

fig2 <- tt_long_post_pre_and_diff %>%
        filter(dep_var_type == plot_dep_var) %>% 
        ggplot(aes(x=reorder(triplet_unique_name,-chose_towards_sparse_avg_across_reps),
                   y=chose_towards_sparse_avg_across_reps,
                   fill=counterbalancing)) +
        geom_boxplot(fatten = 6, aes(color=curve_type)) + 
        stat_summary(fun=mean,
                     geom = 'point',
                     size = 3,
                     color="black",
                     aes(shape = triplet_easiness),
                     position = position_dodge(width = 0.7)) + 
        geom_hline(yintercept = y_intercept, linetype = 'dashed') +
        theme(axis.text.x = element_text(angle = 90),
              legend.position = '') +
        scale_fill_manual(values = c('white','gray')) +
        ylab(paste0(plot_dep_var, '; chose sparse')) +
        xlab('Individual Triplets') +
        ggtitle('All counterbalancing groups')


fig3 <- tt_long_post_pre_and_diff %>%
        filter(dep_var_type == plot_dep_var) %>%
        ggplot(aes(x=reorder(triplet_unique_name,-chose_towards_sparse_avg_across_reps),
                   y=chose_towards_sparse_avg_across_reps)) +
        geom_boxplot(fatten = 6,aes(color=curve_type)) +
        stat_summary(fun=mean,
                     color='black',
                     aes(shape = triplet_easiness),
                     size = 1) +
        geom_hline(yintercept = y_intercept, linetype = 'dashed') +
        theme(axis.text.x = element_text(angle = 90),
              legend.position = '') +
        ylab(paste0(plot_dep_var, '; chose sparse')) +
        xlab('Individual Triplets') +
        ggtitle('Faceting Dense Left & Right') +
        facet_wrap(~counterbalancing, ncol = 1, strip.position = 'right')

grid.arrange(fig1,fig2,fig3,
             nrow = 3,
             heights = c(1,1,2),
             top = 'Chose Sparse')
```

```{r sorted-plot-chose-high-dim-cb-differences, fig.width=13, fig.height=8}


# Unsorted both groups
fig1 <- tt_long_post_pre_and_diff %>%
        filter(dep_var_type == plot_dep_var) %>%
        ggplot(aes(x=triplet_unique_name,
                   y=chose_towards_highdim_avg_across_reps)) +
        geom_boxplot(width = 0.5,
                     fatten = 4,
                     aes(color=curve_type)) +
        stat_summary(fun=mean,
                     color='black',
                     aes(shape = triplet_easiness),
                     size = 0.7,
                     position = position_dodge(width = 0.5)) +
        geom_hline(yintercept = y_intercept, linetype = 'dashed') +
        theme(axis.text.x = element_text(angle = 90),
              legend.position = '') +
        scale_fill_manual(values=c('white','gray')) + 
        ylab(paste0(plot_dep_var, '; chose high-dim')) +
        xlab('Individual Triplets') +
        ggtitle('Both groups') +
        geom_vline(xintercept = seq(0.5,27.5,3), 
                   linetype = 'dashed',
                   alpha = 0.5)


fig2 <- tt_long_post_pre_and_diff %>%
        filter(dep_var_type == plot_dep_var) %>%
        ggplot(aes(x=triplet_unique_name,
                   y=chose_towards_highdim_avg_across_reps,
                   fill=counterbalancing)) +
        geom_boxplot(width = 0.5,
                     fatten = 4,
                     aes(color=curve_type)) +
        stat_summary(fun=mean,
                     color='black',
                     aes(shape = triplet_easiness),
                     size = 0.7,
                     position = position_dodge(width = 0.5)) +
        geom_hline(yintercept = y_intercept, linetype = 'dashed') +
        theme(axis.text.x = element_text(angle = 90),
              legend.position = '') +
        scale_fill_manual(values=c('white','gray')) + 
        ylab(paste0(plot_dep_var, '; chose high-dim')) +
        xlab('Individual Triplets') +
        ggtitle('Both groups') +
        geom_vline(xintercept = seq(0.5,27.5,3), 
                   linetype = 'dashed',
                   alpha = 0.5)

grid.arrange(fig1,fig2,
             nrow = 2,
             top = 'Choose high dimension')

```


# Triplets in density-relative space

```{r density-relative, fig.width=13, fig.height=18}

# For sorted data
fig1 <- tt_long_post_pre_and_diff %>%
        filter(dep_var_type == plot_dep_var) %>% 
        ggplot(aes(x=reorder(density_relative_triplet_name,-chose_towards_sparse_avg_across_reps),
                   y=chose_towards_sparse_avg_across_reps)) +
        geom_boxplot(fatten = 6, aes(color=triplet_location)) + 
        scale_color_manual(values=c("black",
                       "purple",
                       '#ffa303')) +
        stat_summary(fun=mean,
                     geom = 'point',
                     size = 5,
                     color="black",
                     aes(shape = triplet_easiness)) + 
        geom_hline(yintercept = y_intercept, linetype = 'dashed') +
        theme(axis.text.x = element_text(angle = 90),
              legend.position = 'top') +
        ylab(paste0(plot_dep_var, '; chose sparse')) +
        xlab('Density relative triplets!') +
        ggtitle('All counterbalancing groups')

fig2 <- tt_long_post_pre_and_diff %>%
        filter(dep_var_type == plot_dep_var) %>% 
        ggplot(aes(x=reorder(density_relative_triplet_name,-chose_towards_sparse_avg_across_reps),
                   y=chose_towards_sparse_avg_across_reps,
                   fill=counterbalancing)) +
        geom_boxplot(fatten = 6, aes(color=triplet_location)) + 
        scale_color_manual(values=c("black",
                       "purple",
                       '#ffa303')) +        
        stat_summary(fun=mean,
                     geom = 'point',
                     size = 3,
                     color="black",
                     aes(shape = triplet_easiness),
                     position = position_dodge(width = 0.7)) + 
        geom_hline(yintercept = y_intercept, linetype = 'dashed') +
        theme(axis.text.x = element_text(angle = 90),
              legend.position = '') +
        scale_fill_manual(values = c('white','gray')) +
        ylab(paste0(plot_dep_var, '; chose sparse')) +
        xlab('Density relative triplets!') +
        ggtitle('All counterbalancing groups')


fig3 <- tt_long_post_pre_and_diff %>%
        filter(dep_var_type == plot_dep_var) %>%
        ggplot(aes(x=reorder(density_relative_triplet_name,-chose_towards_sparse_avg_across_reps),
                   y=chose_towards_sparse_avg_across_reps)) +
        geom_boxplot(fatten = 6,aes(color=triplet_location)) +
        scale_color_manual(values=c("black",
                       "purple",
                       '#ffa303')) +        
        stat_summary(fun=mean,
                     color='black',
                     aes(shape = triplet_easiness),
                     size = 1) +
        geom_hline(yintercept = y_intercept, linetype = 'dashed') +
        theme(axis.text.x = element_text(angle = 90),
              legend.position = '') +
        ylab(paste0(plot_dep_var, '; chose sparse')) +
        xlab('Density relative triplets!') +
        ggtitle('Dense Left & Right') +
        facet_wrap(~counterbalancing, ncol = 1, strip.position = 'right')

grid.arrange(fig1,fig2,fig3,
             nrow = 3,
             heights = c(1,1,2),
             top = 'DENSITY RELATIVE. Chose Sparse')
```

```{r density-relative-unsorted, fig.width=13, fig.height=18}

# For sorted data
fig1 <- tt_long_post_pre_and_diff %>%
        filter(dep_var_type == plot_dep_var) %>% 
        ggplot(aes(x=density_relative_triplet_name,
                   y=chose_towards_sparse_avg_across_reps)) +
        geom_boxplot(fatten = 6, aes(color=triplet_location)) + 
        scale_color_manual(values=c("black",
                       "purple",
                       '#ffa303')) +
        stat_summary(fun=mean,
                     geom = 'point',
                     size = 5,
                     color="black",
                     aes(shape = triplet_easiness)) + 
        geom_hline(yintercept = y_intercept, linetype = 'dashed') +
        theme(axis.text.x = element_text(angle = 90),
              legend.position = 'top') +
        ylab(paste0(plot_dep_var, '; chose sparse')) +
        xlab('Density relative triplets!') +
        ggtitle('All counterbalancing groups')+
        geom_vline(xintercept = seq(0.5,27.5,3), 
                   linetype = 'dashed',
                   alpha = 0.5)

fig2 <- tt_long_post_pre_and_diff %>%
        filter(dep_var_type == plot_dep_var) %>% 
        ggplot(aes(x=density_relative_triplet_name,
                   y=chose_towards_sparse_avg_across_reps,
                   fill=counterbalancing)) +
        geom_boxplot(fatten = 6, aes(color=triplet_location)) + 
        scale_color_manual(values=c("black",
                       "purple",
                       '#ffa303')) +        
        stat_summary(fun=mean,
                     geom = 'point',
                     size = 3,
                     color="black",
                     aes(shape = triplet_easiness),
                     position = position_dodge(width = 0.7)) + 
        geom_hline(yintercept = y_intercept, linetype = 'dashed') +
        theme(axis.text.x = element_text(angle = 90),
              legend.position = '') +
        scale_fill_manual(values = c('white','gray')) +
        ylab(paste0(plot_dep_var, '; chose sparse')) +
        xlab('Density relative triplets!') +
        ggtitle('All counterbalancing groups') +
        geom_vline(xintercept = seq(0.5,27.5,3), 
                   linetype = 'dashed',
                   alpha = 0.5)


fig3 <- tt_long_post_pre_and_diff %>%
        filter(dep_var_type == plot_dep_var) %>%
        ggplot(aes(x=density_relative_triplet_name,
                   y=chose_towards_sparse_avg_across_reps)) +
        geom_boxplot(fatten = 6,aes(color=triplet_location)) +
        scale_color_manual(values=c("black",
                       "purple",
                       '#ffa303')) +        
        stat_summary(fun=mean,
                     color='black',
                     aes(shape = triplet_easiness),
                     size = 1) +
        geom_hline(yintercept = y_intercept, linetype = 'dashed') +
        theme(axis.text.x = element_text(angle = 90),
              legend.position = '') +
        ylab(paste0(plot_dep_var, '; chose sparse')) +
        xlab('Density relative triplets!') +
        ggtitle('Both groups faceted') +
        facet_wrap(~counterbalancing, ncol = 1, strip.position = 'right') +
        geom_vline(xintercept = seq(0.5,27.5,3), 
                   linetype = 'dashed',
                   alpha = 0.5)

grid.arrange(fig1,fig2,fig3,
             nrow = 3,
             heights = c(1,1,2),
             top = 'DENSITY RELATIVE. Chose Sparse')
```

# Regional analysis: across minus other areas

## Violin plots


```{r triplet-location-differences, fig.width=12, fig.height=3, warning=F}

x_font_size <- 10
x_font_angle <- 20

# Now plot this
fig1 <- tt_part_sum_stats_triplet_location_differences %>%
        filter(dep_var_type == plot_dep_var,
               chose_towards_type == 'chose_towards_sparse') %>% 
        ggplot(aes(x=difference_type,
                   y=difference_value)) +
        geom_violin(fill = chose_sparse_color,alpha = 0.2) +
        geom_boxplot(width=0.2,
                     outlier.shape = '', fatten = 4) +
        geom_jitter(width = 0.05,
                    height = 0,
                    alpha = 0.3) + 
        # geom_line(aes(group=prolific_id),
        #           alpha = 0.2) +  
        stat_summary(fun = mean,
                     color = 'red') + 
        stat_summary(fun.data = mean_cl_normal,
             geom = "errorbar",
             size=0.5,
             width=0.1,
             color='red') + 
        geom_hline(yintercept = 0, linetype = 'dashed') +      
        theme(text = element_text(size=x_font_size)) + 
        # facet_wrap(~counterbalancing) +
        theme(axis.text.x = element_text(angle = x_font_angle)) + 
        ggtitle(paste0(plot_dep_var, ': chose towards sparse. Diff scores'))

# Now plot this
fig2 <- tt_part_sum_stats_triplet_location_differences %>%
        filter(dep_var_type == plot_dep_var,
               chose_towards_type == 'chose_towards_sparse') %>% 
        ggplot(aes(x=difference_type,
                   y=difference_value)) +
        geom_violin(fill = chose_sparse_color,alpha = 0.2) +
        geom_boxplot(width=0.2,
                     outlier.shape = '', fatten = 4) +
        geom_jitter(width = 0.05,
                    height = 0,
                    alpha = 0.3) + 
        # geom_line(aes(group=prolific_id),
        #           alpha = 0.2) +  
        stat_summary(fun = mean,
                     color = 'red') + 
        stat_summary(fun.data = mean_cl_normal,
             geom = "errorbar",
             size=0.5,
             width=0.1,
             color='red') + 
        geom_hline(yintercept = 0, linetype = 'dashed') +      
        theme(text = element_text(size=x_font_size)) + 
        facet_wrap(~counterbalancing) +
        theme(axis.text.x = element_text(angle = x_font_angle))


grid.arrange(fig1,fig2,
             nrow = 1,
             widths = 1:2)

```

```{r triplet-location-differences-easiness-levels, fig.width=12, fig.height=6, warning=F}

x_font_size <- 10
x_font_angle <- 20

# Now plot this
fig1 <- tt_part_sum_stats_triplet_location_easiness_differences %>%
        filter(dep_var_type == plot_dep_var,
               chose_towards_type == 'chose_towards_sparse') %>% 
        ggplot(aes(x=difference_type,
                   y=difference_value)) +
        geom_violin(fill = chose_sparse_color,alpha = 0.2) +
        geom_boxplot(width=0.2,
                     outlier.shape = '', fatten = 4) +
        geom_jitter(width = 0.05,
                    height = 0,
                    alpha = 0.3) + 
        # geom_line(aes(group=prolific_id),
        #           alpha = 0.2) +  
        stat_summary(fun = mean,
                     color = 'red') + 
        stat_summary(fun.data = mean_cl_normal,
             geom = "errorbar",
             size=0.5,
             width=0.1,
             color='red') + 
        geom_hline(yintercept = 0, linetype = 'dashed') +      
        theme(text = element_text(size=x_font_size)) + 
        facet_wrap(~triplet_easiness, ncol = 1, strip.position = 'right') +
        theme(axis.text.x = element_text(angle = x_font_angle)) + 
        ggtitle(paste0(plot_dep_var, '. chose towards sparse. Diff scores'))

# Now plot this
fig2 <- tt_part_sum_stats_triplet_location_easiness_differences %>%
        filter(dep_var_type == plot_dep_var,
               chose_towards_type == 'chose_towards_sparse') %>% 
        ggplot(aes(x=difference_type,
                   y=difference_value)) +
        geom_violin(fill = chose_sparse_color,alpha = 0.2) +
        geom_boxplot(width=0.2,
                     outlier.shape = '', fatten = 4) +
        geom_jitter(width = 0.05,
                    height = 0,
                    alpha = 0.3) + 
        # geom_line(aes(group=prolific_id),
        #           alpha = 0.2) +  
        stat_summary(fun = mean,
                     color = 'red') + 
        stat_summary(fun.data = mean_cl_normal,
             geom = "errorbar",
             size=0.5,
             width=0.1,
             color='red') + 
        geom_hline(yintercept = 0, linetype = 'dashed') +      
        theme(text = element_text(size=x_font_size)) + 
        facet_wrap(~counterbalancing) +
        facet_grid(triplet_easiness~counterbalancing) +
        theme(axis.text.x = element_text(angle = x_font_angle))


grid.arrange(fig1,fig2,
             nrow = 1,
             widths = 1:2)

```


## Across minus dense

```{r sorted-plot-triplet-location-diff-socres-1, fig.width=8, fig.height=20}

# For sorted data

fig1 <- tt_part_sum_stats_triplet_location_template_differences %>%
        filter(dep_var_type == plot_dep_var,
               difference_type == 'across_minus_dense',
               chose_towards_type == 'chose_towards_sparse') %>% 
        ggplot(aes(x=reorder(template_distances,-difference_value),
                   y=difference_value)) +
        geom_boxplot(fatten = 4,aes(color=template_distances)) + 
        stat_summary(fun=mean,color='black',
                     aes(shape = triplet_easiness),
                     size = 1) + 
        geom_hline(yintercept = 0, linetype = 'dashed') +
        theme(axis.text.x = element_text(angle = 90),
              legend.position = '') + 
        ylab('Across-Dense:\n Post-pre chose low-density') + 
        xlab('Templates') +
        ggtitle('Both counterbalancing groups')

fig2 <- tt_part_sum_stats_triplet_location_template_differences %>%
        filter(dep_var_type == plot_dep_var,
               difference_type == 'across_minus_dense',
               chose_towards_type == 'chose_towards_sparse') %>%
        ggplot(aes(x=reorder(template_distances,-difference_value),
                   y=difference_value,
                   fill=counterbalancing)) +
        geom_boxplot(fatten = 4,aes(color=template_distances)) + 
        stat_summary(fun=mean,color='black',
                     aes(shape = triplet_easiness),
                     size = 1,
                     position = position_dodge(width = 0.7)) + 
        scale_fill_manual(values = c('white','gray')) +
        geom_hline(yintercept = 0, linetype = 'dashed') +
        theme(axis.text.x = element_text(angle = 90),
              legend.position = '') + 
        ylab('Across-Dense:\n Post-pre chose low-density') + 
        xlab('Templates') +
        ggtitle('Both counterbalancing groups')


fig3 <- tt_part_sum_stats_triplet_location_template_differences %>%
        filter(counterbalancing == 'dense_right',
               dep_var_type == plot_dep_var,
               difference_type == 'across_minus_dense',
               chose_towards_type == 'chose_towards_sparse') %>%
        ggplot(aes(x=reorder(template_distances,-difference_value),
                   y=difference_value)) +
        geom_boxplot(fatten = 4,aes(color=template_distances)) + 
        stat_summary(fun=mean,color='black',
                     aes(shape = triplet_easiness),
                     size = 1) +
        geom_hline(yintercept = 0, linetype = 'dashed') +
        theme(axis.text.x = element_text(angle = 90),
              legend.position = '') + 
        ylab('Across-Dense:\n Post-pre chose low-density') + 
        xlab('Templates') +
        ggtitle('Dense Right')

fig4 <- tt_part_sum_stats_triplet_location_template_differences %>%
        filter(counterbalancing == 'dense_left',
               dep_var_type == plot_dep_var,
               difference_type == 'across_minus_dense',
               chose_towards_type == 'chose_towards_sparse') %>%
        ggplot(aes(x=reorder(template_distances,-difference_value),
                   y=difference_value)) +
        geom_boxplot(fatten = 4,aes(color=template_distances)) + 
        stat_summary(fun=mean,color='black',
                     aes(shape = triplet_easiness),
                     size = 1) +
        geom_hline(yintercept = 0, linetype = 'dashed') +
        theme(axis.text.x = element_text(angle = 90),
              legend.position = '') + 
        ylab('Across-Dense:\n Post-pre chose low-density') + 
        xlab('Templates') +
        ggtitle('Dense Left')
        

grid.arrange(fig1,fig2,fig3,fig4,
             nrow = 4,
             top = 'Across - Dense')


```



## Across minus sparse

```{r sorted-plot-triplet-location-diff-socres-2, fig.width=8, fig.height=20}

# For sorted data

fig1 <- tt_part_sum_stats_triplet_location_template_differences %>%
        filter(dep_var_type == 'post_pre_diff',
               difference_type == 'across_minus_sparse',
               chose_towards_type == 'chose_towards_sparse') %>%
        ggplot(aes(x=reorder(template_distances,-difference_value),
                   y=difference_value)) +
        geom_boxplot(fatten = 4,aes(color=template_distances)) + 
        stat_summary(fun=mean,color='black',
                     aes(shape = triplet_easiness),
                     size = 1) + 
        geom_hline(yintercept = 0, linetype = 'dashed') +
        theme(axis.text.x = element_text(angle = 90),
              legend.position = '') + 
        ylab('Across-Sparse:\n Post-pre chose low-density') + 
        xlab('Templates') +
        ggtitle('Both counterbalancing groups')

fig2 <- tt_part_sum_stats_triplet_location_template_differences %>%
        filter(dep_var_type == plot_dep_var,
               difference_type == 'across_minus_sparse',
               chose_towards_type == 'chose_towards_sparse') %>%
        ggplot(aes(x=reorder(template_distances,-difference_value),
                   y=difference_value,
                   fill=counterbalancing)) +
        geom_boxplot(fatten = 4,aes(color=template_distances)) + 
        stat_summary(fun=mean,color='black',
                     aes(shape = triplet_easiness),
                     size = 1,
                     position = position_dodge(width = 0.7)) + 
        scale_fill_manual(values = c('white','gray')) +
        geom_hline(yintercept = 0, linetype = 'dashed') +
        theme(axis.text.x = element_text(angle = 90),
              legend.position = '') + 
        ylab('Across-Dense:\n Post-pre chose low-density') + 
        xlab('Templates') +
        ggtitle('Both counterbalancing groups')

fig3 <- tt_part_sum_stats_triplet_location_template_differences %>%
        filter(counterbalancing == 'dense_right',
               dep_var_type == 'post_pre_diff',
               difference_type == 'across_minus_sparse',
               chose_towards_type == 'chose_towards_sparse') %>%
        ggplot(aes(x=reorder(template_distances,-difference_value),
                   y=difference_value)) +
        geom_boxplot(fatten = 4,aes(color=template_distances)) + 
        stat_summary(fun=mean,color='black',
                     aes(shape = triplet_easiness),
                     size = 1) +
        geom_hline(yintercept = 0, linetype = 'dashed') +
        theme(axis.text.x = element_text(angle = 90),
              legend.position = '') + 
        ylab('Across-Sparse:\n Post-pre chose low-density') + 
        xlab('Templates') +
        ggtitle('Dense Right')

fig4 <- tt_part_sum_stats_triplet_location_template_differences %>%
        filter(counterbalancing == 'dense_left',
               dep_var_type == 'post_pre_diff',
               difference_type == 'across_minus_sparse',
               chose_towards_type == 'chose_towards_sparse') %>%
        ggplot(aes(x=reorder(template_distances,-difference_value),
                   y=difference_value)) +
        geom_boxplot(fatten = 4,aes(color=template_distances)) + 
        stat_summary(fun=mean,color='black',
                     aes(shape = triplet_easiness),
                     size = 1) +
        geom_hline(yintercept = 0, linetype = 'dashed') +
        theme(axis.text.x = element_text(angle = 90),
              legend.position = '') + 
        ylab('Across-Sparse:\n Post-pre chose low-density') + 
        xlab('Templates') +
        ggtitle('Dense Left')
        

grid.arrange(fig1,fig2,fig3,fig4,
             nrow = 4,
             top = 'Across - Sparse')

```


## Across minus avg(dense,sparse)

```{r sorted-plot-triplet-location-diff-socres-1, fig.width=8, fig.height=15}


```














