---
title: "TT Overall Overview"
output:
  html_document:
    number_sections: false
    
knit: (function(input, ...) {
    rmarkdown::render(
      input,
      knit_root_dir = rprojroot::find_rstudio_root_file(),
      output_file = paste0(
      rprojroot::find_rstudio_root_file(),
      '/results/pilots/',
      'pilot_sort_x_axis_paradigm_3_qc_filtered_',Sys.Date(),'.html'

      ),
      envir = globalenv()
    )
  })
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

# Suppress summarise info
options(dplyr.summarise.inform = FALSE)

```

```{r load-libraries}

# Clean the environment and load libraries ############################

rm(list=ls())

source('./scripts/utils/load_all_libraries.R')

```

# Load the data and set flags

(code hidden)

```{r load-transform-tt-data}

qc_filter <- T
print(paste0('QC filter? ', qc_filter))


which_paradigm <- c(4)

print(paste0('Which pilot paradigm? ', which_paradigm))

# Which participants to analyze?
exclude_participants <- F
ptp_min_idx <- 1
ptp_max_idx <- 57

source('./scripts/utils/load_transform_tt_data_pilots.R')
source('./scripts/utils/summary_stats_for_various_factors.R')

# Flags and settings

chose_sparse_color  <- 'blue'
chose_highdim_color <- 'green'
accuracy_color      <- 'yellow'

# Show the basic table
tt_long %>%
        filter(trial_index == 1,session == 1,trial_stage == 'pre_exposure') %>%
        group_by(counterbalancing,
                 prolific_id) %>%
        summarise(n = n()) %>%
        knitr::kable(caption = 'Participants and counterbalancing') %>%
        kable_styling(bootstrap_options = "striped")

```

# Plots with x axis sorted by diagnosticity

## Y axis: post-pre chose high-dimension

```{r sorted-plot-chose-high-dimension, fig.width=13, fig.height=18}

# For sorted data
fig1 <- tt_long_post_pre_and_diff %>%
        filter(dep_var_type == 'post_pre_diff') %>% 
        ggplot(aes(x=reorder(triplet_unique_name,-chose_towards_highdim_avg_across_reps),
                   y=chose_towards_highdim_avg_across_reps)) +
        geom_boxplot(fatten = 3) + 
        stat_summary(fun=mean,
                     geom = 'point',
                     size = 5,
                     color="black",
                     aes(shape = triplet_easiness)) + 
        geom_hline(yintercept = 0, linetype = 'dashed') +
        theme(axis.text.x = element_text(angle = 90),
              legend.position = 'top') +
        ylab('Post-pre: chose high-dim') + 
        xlab('Individual Triplets') +
        ggtitle('All counterbalancing groups')



fig2 <- tt_long_post_pre_and_diff %>%
        filter(counterbalancing == 'dense_right',
               dep_var_type == 'post_pre_diff') %>% 
         ggplot(aes(x=reorder(triplet_unique_name,-chose_towards_highdim_avg_across_reps),
                   y=chose_towards_highdim_avg_across_reps)) +
        geom_boxplot(fatten = 4,aes(color=triplet_location)) + 
        stat_summary(fun=mean,
                     color='black',
                     aes(shape = triplet_easiness),
                     size = 1) + 
        geom_hline(yintercept = 0, linetype = 'dashed') +
        # geom_point(data = filter(tt_bw_part_sum_stats_triplets,counterbalancing == 'dense_right'),
        #            aes(x = triplet_unique_name,
        #                y = mean_chose_towards_sparse)) +
        theme(axis.text.x = element_text(angle = 90),
              legend.position = 'top') +
        ylab('Post-pre: chose high-dim') + 
        xlab('Individual Triplets') +
        ggtitle('Dense Right')

fig3 <- tt_long_post_pre_and_diff %>%
        filter(counterbalancing == 'dense_left',
               dep_var_type == 'post_pre_diff') %>%
        ggplot(aes(x=reorder(triplet_unique_name,-chose_towards_highdim_avg_across_reps),
                   y=chose_towards_highdim_avg_across_reps)) +
        geom_boxplot(fatten = 4,aes(color=triplet_location)) +
        stat_summary(fun=mean,
                     color='black',
                     aes(shape = triplet_easiness),
                     size = 1) + 
        geom_hline(yintercept = 0, linetype = 'dashed') +
        theme(axis.text.x = element_text(angle = 90),
              legend.position = '') +
        ylab('Post-pre: chose high-dim') +
        xlab('Individual Triplets') +
        ggtitle('Dense Left')

fig4 <- tt_long_post_pre_and_diff %>%
        filter(dep_var_type == 'post_pre_diff') %>%
        ggplot(aes(x=triplet_unique_name,
                   y=chose_towards_highdim_avg_across_reps,
                   fill=counterbalancing)) +
        geom_boxplot(fatten = 4,
                     aes(color=triplet_location)) +
        stat_summary(fun=mean,
                     color='black',
                     aes(shape = triplet_easiness),
                     size = 0.7,
                     position = position_dodge(width = 0.8)) +
        geom_hline(yintercept = 0, linetype = 'dashed') +
        theme(axis.text.x = element_text(angle = 90),
              legend.position = '') +
        scale_fill_manual(values=c('white','gray')) + 
        ylab('Post-pre: chose high-dim') +
        xlab('Individual Triplets') +
        ggtitle('Both groups')

grid.arrange(fig1,fig2,fig3,fig4,
             nrow = 4)
```


## Y axis: post-pre chose low-density

```{r sorted-plot-chose-low-density, fig.width=13, fig.height=18}

# Calculate the mean data separately

# For sorted data
fig1 <- tt_long_post_pre_and_diff %>%
        filter(dep_var_type == 'post_pre_diff') %>% 
        ggplot(aes(x=reorder(triplet_unique_name,-chose_towards_sparse_avg_across_reps),
                   y=chose_towards_sparse_avg_across_reps)) +
        geom_boxplot(fatten = 3) + 
        stat_summary(fun=mean,
                     geom = 'point',
                     size = 5,
                     color="black",
                     aes(shape = triplet_easiness)) + 
        geom_hline(yintercept = 0, linetype = 'dashed') +
        theme(axis.text.x = element_text(angle = 90),
              legend.position = 'top') +
        ylab('Post-pre: chose low-density') + 
        xlab('Individual Triplets') +
        ggtitle('All counterbalancing groups')



fig2 <- tt_long_post_pre_and_diff %>%
        filter(counterbalancing == 'dense_right',
               dep_var_type == 'post_pre_diff') %>% 
         ggplot(aes(x=reorder(triplet_unique_name,-chose_towards_sparse_avg_across_reps),
                   y=chose_towards_sparse_avg_across_reps)) +
        geom_boxplot(fatten = 4,aes(color=triplet_location)) + 
        stat_summary(fun=mean,
                     color='black',
                     aes(shape = triplet_easiness),
                     size = 1) + 
        geom_hline(yintercept = 0, linetype = 'dashed') +
        # geom_point(data = filter(tt_bw_part_sum_stats_triplets,counterbalancing == 'dense_right'),
        #            aes(x = triplet_unique_name,
        #                y = mean_chose_towards_sparse)) +
        theme(axis.text.x = element_text(angle = 90),
              legend.position = 'top') +
        ylab('Post-pre: chose low-density') + 
        xlab('Individual Triplets') +
        ggtitle('Dense Right')

fig3 <- tt_long_post_pre_and_diff %>%
        filter(counterbalancing == 'dense_left',
               dep_var_type == 'post_pre_diff') %>%
        ggplot(aes(x=reorder(triplet_unique_name,-chose_towards_sparse_avg_across_reps),
                   y=chose_towards_sparse_avg_across_reps)) +
        geom_boxplot(fatten = 4,aes(color=triplet_location)) +
        stat_summary(fun=mean,
                     color='black',
                     aes(shape = triplet_easiness),
                     size = 1) + 
        geom_hline(yintercept = 0, linetype = 'dashed') +
        theme(axis.text.x = element_text(angle = 90),
              legend.position = '') +
        ylab('Post-pre: chose low-density') +
        xlab('Individual Triplets') +
        ggtitle('Dense Left')

fig4 <- tt_long_post_pre_and_diff %>%
        filter(dep_var_type == 'post_pre_diff') %>%
        ggplot(aes(x=triplet_unique_name,
                   y=chose_towards_sparse_avg_across_reps,
                   fill=counterbalancing)) +
        geom_boxplot(fatten = 4,
                     aes(color=triplet_location)) +
        stat_summary(fun=mean,
                     color='black',
                     aes(shape = triplet_easiness),
                     size = 0.7,
                     position = position_dodge(width = 0.8)) +
        geom_hline(yintercept = 0, linetype = 'dashed') +
        theme(axis.text.x = element_text(angle = 90),
              legend.position = '') +
        scale_fill_manual(values=c('white','gray')) + 
        ylab('Post-pre: chose high-dim') +
        xlab('Individual Triplets') +
        ggtitle('Both groups')

grid.arrange(fig1,fig2,fig3,fig4,
             nrow = 4)
```



## Y axis: post-pre chose towards higher dimension, between counterbalancing groups

```{r sorted-plot-chose-low-density-cb-differences, fig.width=13, fig.height=3}

tt_bw_part_sum_stats_triplets_difference %>%
        filter(dep_var_type == 'post_pre_diff',
               measure_type == 'chose_towards_highdim') %>%
        ggplot(aes(x=reorder(triplet_unique_name,-difference_value),
                   y=difference_value)) +
        geom_hline(yintercept = 0, linetype = 'dashed') +
        geom_point(aes(color = triplet_easiness,
                       shape = curve_type),
                   size = 3) +
        theme(axis.text.x = element_text(angle = 90),
              legend.position = 'right') +
        ylab('Dense_right - Dense_left') + 
        xlab('Individual Triplets') +
        ggtitle('Post-pre chose high-dimension: Counterbalancing group difference')

# Unsorted
tt_bw_part_sum_stats_triplets_difference %>%
        filter(dep_var_type == 'post_pre_diff',
               measure_type == 'chose_towards_highdim') %>%
        ggplot(aes(x=triplet_unique_name,
                   y=difference_value)) +
        geom_hline(yintercept = 0, linetype = 'dashed') +
        geom_point(aes(color = triplet_easiness,
                       shape = curve_type),
                   size = 3) +
        theme(axis.text.x = element_text(angle = 90),
              legend.position = 'right') +
        ylab('Dense_right - Dense_left') + 
        xlab('Individual Triplets') +
        ggtitle('(UNSORTED) Post-pre chose high-dimension: Counterbalancing group difference')

# Unsorted absolute value
tt_bw_part_sum_stats_triplets_difference %>%
        filter(dep_var_type == 'post_pre_diff',
               measure_type == 'chose_towards_highdim') %>%
        ggplot(aes(x=triplet_unique_name,
                   y=abs(difference_value))) +
        geom_hline(yintercept = 0, linetype = 'dashed') +
        geom_point(aes(color = triplet_easiness,
                       shape = curve_type),
                   size = 3) +
        theme(axis.text.x = element_text(angle = 90),
              legend.position = 'right') +
        ylab('Dense_right - Dense_left') + 
        xlab('Individual Triplets') +
        ggtitle('(UNSORTED ABS) Post-pre chose high-dimension: Counterbalancing group difference')


```


## Y axis: triplet_location differences in their post-pre value

```{r sorted-plot-triplet-location-diff-socres-1, fig.width=8, fig.height=15}

# For sorted data

fig1 <- tt_part_sum_stats_triplet_location_template_differences %>%
        filter(dep_var_type == 'post_pre_diff',
               difference_type == 'across_minus_dense',
               measure_type == 'chose_towards_sparse') %>%
        ggplot(aes(x=reorder(template_distances,-difference_value),
                   y=difference_value)) +
        geom_boxplot(fatten = 4,aes(color=template_distances)) + 
        stat_summary(fun=mean,color='black',
                     aes(shape = triplet_easiness),
                     size = 1) + 
        geom_hline(yintercept = 0, linetype = 'dashed') +
        theme(axis.text.x = element_text(angle = 90),
              legend.position = 'right') + 
        ylab('Across-Dense:\n Post-pre chose low-density') + 
        xlab('Templates') +
        ggtitle('Both counterbalancing groups')


fig2 <- tt_part_sum_stats_triplet_location_template_differences %>%
        filter(counterbalancing == 'dense_right',
               dep_var_type == 'post_pre_diff',
               difference_type == 'across_minus_dense',
               measure_type == 'chose_towards_sparse') %>%
        ggplot(aes(x=reorder(template_distances,-difference_value),
                   y=difference_value)) +
        geom_boxplot(fatten = 4,aes(color=template_distances)) + 
        stat_summary(fun=mean,color='black',
                     aes(shape = triplet_easiness),
                     size = 1) +
        geom_hline(yintercept = 0, linetype = 'dashed') +
        theme(axis.text.x = element_text(angle = 90),
              legend.position = '') + 
        ylab('Across-Dense:\n Post-pre chose low-density') + 
        xlab('Templates') +
        ggtitle('Dense Right')

fig3 <- tt_part_sum_stats_triplet_location_template_differences %>%
        filter(counterbalancing == 'dense_left',
               dep_var_type == 'post_pre_diff',
               difference_type == 'across_minus_dense',
               measure_type == 'chose_towards_sparse') %>%
        ggplot(aes(x=reorder(template_distances,-difference_value),
                   y=difference_value)) +
        geom_boxplot(fatten = 4,aes(color=template_distances)) + 
        stat_summary(fun=mean,color='black',
                     aes(shape = triplet_easiness),
                     size = 1) +
        geom_hline(yintercept = 0, linetype = 'dashed') +
        theme(axis.text.x = element_text(angle = 90),
              legend.position = '') + 
        ylab('Across-Dense:\n Post-pre chose low-density') + 
        xlab('Templates') +
        ggtitle('Dense Left')
        

grid.arrange(fig1,fig2,fig3,
             nrow = 3,
             top = 'Across - Dense')
```

```{r sorted-plot-triplet-location-diff-socres-2, fig.width=8, fig.height=15}

# For sorted data

fig1 <- tt_part_sum_stats_triplet_location_template_differences %>%
        filter(dep_var_type == 'post_pre_diff',
               difference_type == 'across_minus_sparse',
               measure_type == 'chose_towards_sparse') %>%
        ggplot(aes(x=reorder(template_distances,-difference_value),
                   y=difference_value)) +
        geom_boxplot(fatten = 4,aes(color=template_distances)) + 
        stat_summary(fun=mean,color='black',
                     aes(shape = triplet_easiness),
                     size = 1) + 
        geom_hline(yintercept = 0, linetype = 'dashed') +
        theme(axis.text.x = element_text(angle = 90),
              legend.position = 'right') + 
        ylab('Across-Sparse:\n Post-pre chose low-density') + 
        xlab('Templates') +
        ggtitle('Both counterbalancing groups')


fig2 <- tt_part_sum_stats_triplet_location_template_differences %>%
        filter(counterbalancing == 'dense_right',
               dep_var_type == 'post_pre_diff',
               difference_type == 'across_minus_sparse',
               measure_type == 'chose_towards_sparse') %>%
        ggplot(aes(x=reorder(template_distances,-difference_value),
                   y=difference_value)) +
        geom_boxplot(fatten = 4,aes(color=template_distances)) + 
        stat_summary(fun=mean,color='black',
                     aes(shape = triplet_easiness),
                     size = 1) +
        geom_hline(yintercept = 0, linetype = 'dashed') +
        theme(axis.text.x = element_text(angle = 90),
              legend.position = '') + 
        ylab('Across-Sparse:\n Post-pre chose low-density') + 
        xlab('Templates') +
        ggtitle('Dense Right')

fig3 <- tt_part_sum_stats_triplet_location_template_differences %>%
        filter(counterbalancing == 'dense_left',
               dep_var_type == 'post_pre_diff',
               difference_type == 'across_minus_sparse',
               measure_type == 'chose_towards_sparse') %>%
        ggplot(aes(x=reorder(template_distances,-difference_value),
                   y=difference_value)) +
        geom_boxplot(fatten = 4,aes(color=template_distances)) + 
        stat_summary(fun=mean,color='black',
                     aes(shape = triplet_easiness),
                     size = 1) +
        geom_hline(yintercept = 0, linetype = 'dashed') +
        theme(axis.text.x = element_text(angle = 90),
              legend.position = '') + 
        ylab('Across-Sparse:\n Post-pre chose low-density') + 
        xlab('Templates') +
        ggtitle('Dense Left')
        

grid.arrange(fig1,fig2,fig3,
             nrow = 3,
             top = 'Across - Sparse')
```

