---
title: "TT Overall Overview"
output:
  html_document:
    number_sections: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r load-libraries}

# Clean the environment and load libraries ############################

rm(list=ls())

pacman::p_load(pacman,
               rio,
               tidyverse,
               rstatix,
               DT,
               kableExtra,
               readr,
               writexl,
               jsonlite,
               stringr,
               gridExtra,
               knitr,
               magrittr,
               Hmisc,
               psycho)

```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

# Suppress summarise info
options(dplyr.summarise.inform = FALSE)

```

```{r load-libraries}

# Clean the environment and load libraries ############################

rm(list=ls())

pacman::p_load(pacman,
               rio,
               tidyverse,
               rstatix,
               DT,
               kableExtra,
               readr,
               writexl,
               jsonlite,
               stringr,
               gridExtra,
               knitr,
               magrittr,
               Hmisc,
               psycho)

```

```{r load-transform-tt-data}

qc_filter = T
print(paste0('QC filter? ', qc_filter))

source('./scripts/utils/load_transform_tt_data.R')

# Flags and settings

chose_sparse_color  <- 'blue'
chose_highdim_color <- 'green'
accuracy_color      <- 'yellow'

# Show the basic table
tt_long %>%
        filter(trial_index == 1,session == 1,trial_stage == 'pre_exposure') %>%
        group_by(counterbalancing,
                 prolific_id) %>%
        summarise(n = n()) %>%
        knitr::kable(caption = 'Participants and counterbalancing') %>%
        kable_styling(bootstrap_options = "striped")

```

# Summary stats for various combinations of factors.

(Code hidden)
Calculates some tables for plotting them below.

```{r part-specific-summary-stats}

# Create participant summary stats
tt_participant_summary_stats <- tt_long_post_pre_and_diff %>%
        group_by(prolific_id,
                 counterbalancing,
                 dep_var_type) %>%
        summarise(n_datapoints = n(),
                  mean_choice_sum = mean(choice_numeric_sum_across_reps),
                  mean_chose_towards_sparse = mean(chose_towards_sparse_avg_across_reps),
                  mean_chose_towards_highdim = mean(chose_towards_highdim_avg_across_reps),
                  mean_correct = mean(correct_avg_across_reps, na.rm = T)) %>%
        ungroup()

tt_participant_summary_stats_triplet_location <- tt_long_post_pre_and_diff %>%
        group_by(prolific_id,
                 counterbalancing,
                 triplet_location,
                 dep_var_type) %>%
        summarise(n_datapoints = n(),
                  mean_choice_sum = mean(choice_numeric_sum_across_reps),
                  mean_chose_towards_sparse = mean(chose_towards_sparse_avg_across_reps),
                  mean_chose_towards_highdim = mean(chose_towards_highdim_avg_across_reps),
                  mean_correct = mean(correct_avg_across_reps, na.rm = T)) %>%
        ungroup()

tt_participant_summary_stats_curve_type <- tt_long_post_pre_and_diff %>%
        group_by(prolific_id,
                 counterbalancing,
                 curve_type,
                 dep_var_type) %>%
        summarise(n_datapoints = n(),
                  mean_choice_sum = mean(choice_numeric_sum_across_reps),
                  mean_chose_towards_sparse = mean(chose_towards_sparse_avg_across_reps),
                  mean_chose_towards_highdim = mean(chose_towards_highdim_avg_across_reps),
                  mean_correct = mean(correct_avg_across_reps, na.rm = T)) %>%
        ungroup()

tt_participant_summary_stats_triplet_location_easiness <- tt_long_post_pre_and_diff %>%
        group_by(prolific_id,
                 counterbalancing,
                 triplet_location,
                 triplet_easiness,
                 dep_var_type) %>%
        summarise(n_datapoints = n(),
                  mean_choice_sum = mean(choice_numeric_sum_across_reps),
                  mean_chose_towards_sparse = mean(chose_towards_sparse_avg_across_reps),
                  mean_chose_towards_highdim = mean(chose_towards_highdim_avg_across_reps),
                  mean_correct = mean(correct_avg_across_reps, na.rm = T)) %>%
        ungroup()

tt_participant_summary_stats_template_triplet_location_easiness <- tt_long_post_pre_and_diff %>%
        group_by(prolific_id,
                 counterbalancing,
                 template_distances,
                 triplet_location,
                 triplet_easiness,
                 dep_var_type) %>%
        summarise(n_datapoints = n(),
                  mean_choice_sum = mean(choice_numeric_sum_across_reps),
                  mean_chose_towards_sparse = mean(chose_towards_sparse_avg_across_reps),
                  mean_chose_towards_highdim = mean(chose_towards_highdim_avg_across_reps),
                  mean_correct = mean(correct_avg_across_reps, na.rm = T)) %>%
        ungroup()

tt_participant_summary_stats_curve_type_template <- tt_long_post_pre_and_diff %>%
        group_by(prolific_id,
                 counterbalancing,
                 curve_type,
                 template_distances,
                 dep_var_type) %>%
        summarise(n_datapoints = n(),
                  mean_choice_sum = mean(choice_numeric_sum_across_reps),
                  mean_chose_towards_sparse = mean(chose_towards_sparse_avg_across_reps),
                  mean_chose_towards_highdim = mean(chose_towards_highdim_avg_across_reps),
                  mean_correct = mean(correct_avg_across_reps, na.rm = T)) %>%
        ungroup()

tt_participant_summary_stats_triplet_location_template <- tt_long_post_pre_and_diff %>%
        group_by(prolific_id,
                 counterbalancing,
                 triplet_location,
                 template_distances,
                 dep_var_type) %>%
        summarise(n_datapoints = n(),
                  mean_choice_sum = mean(choice_numeric_sum_across_reps),
                  mean_chose_towards_sparse = mean(chose_towards_sparse_avg_across_reps),
                  mean_chose_towards_highdim = mean(chose_towards_highdim_avg_across_reps),
                  mean_correct = mean(correct_avg_across_reps, na.rm = T)) %>%
        ungroup()

```


# Plots over all trials, all dependent variables

```{r all-dep-var-overall-plots, fig.height=4, fig.width=9, warning=F}

# # Choice towards sparse
# fig3 <- tt_participant_summary_stats_triplet_location %>%
#         #filter(dep_var_type == 'post_pre_diff') %>% 
#         ggplot(aes(x=dep_var_type,
#                    y=mean_chose_towards_sparse)) +
#         geom_violin() +
#         geom_boxplot(width=0.2,○
#         geom_jitter(width = 0.05,
#                     height = 0,
#                     alpha = 0.3) + 
#         geom_line(aes(group=prolific_id),
#                   alpha = 0.2) +  
#         stat_summary(fun = mean,
#                      color = 'red') + geom_hline(yintercept = 0, linetype = 'dashed') +       
#         facet_grid(~triplet_location) +
#         theme(axis.text.x = element_text(angle = 90)) +
#         ggtitle('chose towards sparse')

# fig4 <- tt_participant_summary_stats_triplet_location %>%
#         #filter(dep_var_type == 'post_pre_diff') %>% 
#         ggplot(aes(x=dep_var_type,
#                    y=mean_chose_towards_sparse)) +
#         geom_violin() +
#         geom_boxplot(width=0.15,
#                      outlier.shape = '', fatten = 4) +
#         geom_jitter(width = 0.05,
#                     height = 0,
#                     alpha = 0.3) +
#         geom_line(aes(group=prolific_id),
#                   alpha = 0.2) +        
#         stat_summary(fun = mean,
#                      color = 'red') + geom_hline(yintercept = 0, linetype = 'dashed') +         
#         facet_grid(~counterbalancing+triplet_location) +
#         theme(axis.text.x = element_text(angle = 90))
# 
# print(fig4)

# # Choice sum
# fig5 <- tt_participant_summary_stats_triplet_location %>%
#         #filter(dep_var_type == 'post_pre_diff') %>% 
#         ggplot(aes(x=dep_var_type,
#                    y=mean_chose_towards_highdim)) +
#         geom_violin() +
#         geom_boxplot(width=0.2,
#                      outlier.shape = '', fatten = 4) +
#         geom_jitter(width = 0.05,
#                     height = 0,
#                     alpha = 0.3) + 
#         geom_line(aes(group=prolific_id),
#                   alpha = 0.2) +     
#         stat_summary(fun = mean,
#                      color = 'red') + geom_hline(yintercept = 0, linetype = 'dashed') + 
#         facet_grid(~triplet_location) +
#         ggtitle('chose towards high dimension') + 
#         theme(axis.text.x = element_text(angle = 90))
# 
fig6 <- tt_participant_summary_stats_triplet_location %>%
        #filter(dep_var_type == 'post_pre_diff') %>%
        ggplot(aes(x=dep_var_type,
                   y=mean_chose_towards_highdim)) +
        geom_violin() +
        geom_boxplot(width=0.15,
                     outlier.shape = '', fatten = 4) +
        geom_jitter(width = 0.05,
                    height = 0,
                    alpha = 0.3) +
        geom_line(aes(group=prolific_id),
                  alpha = 0.2) +
        stat_summary(fun = mean,
                     color = 'red') + geom_hline(yintercept = 0, linetype = 'dashed') +
        facet_grid(~counterbalancing+triplet_location) +
        theme(axis.text.x = element_text(angle = 90))

print(fig6)

# grid.arrange(fig3,fig4,
#              fig5,fig6,
#              nrow = 2,
#              widths = 1:2)
             


```

